### ISSUE TITLE
Doesn't work with `None` skin tone

### ISSUE THREAD

**Issue by daronspence** [fedecalendino/alfred-emoji-mate#10]
Debug output from Alfred

```
[09:57:23.159] ERROR: Emoji Mate[Script Filter] Code 1: Traceback (most recent call last):
  File "./dist/main.py", line 4, in <module>
    from emojis import emojis
  File "/Users/daron/Library/Mobile Documents/com~apple~CloudDocs/Alfred Sync/Alfred.alfredpreferences/workflows/user.workflow.14BEC03F-13E2-4356-8D6F-D9198A146E94/dist/emojis.py", line 96, in <module>
    emojis = list(build())
  File "/Users/daron/Library/Mobile Documents/com~apple~CloudDocs/Alfred Sync/Alfred.alfredpreferences/workflows/user.workflow.14BEC03F-13E2-4356-8D6F-D9198A146E94/dist/emojis.py", line 49, in build
    if skin_tone not in key:
TypeError: 'in <string>' requires string as left operand, not NoneType
```

![CleanShot 2022-12-22 at 09 58 48](https://user-images.githubusercontent.com/4062087/209097088-77d2a8b4-564b-4ce0-a9d9-c3895bff1d5e.png)

If I choose a skin tone, it works.

**Comment by fedecalendino** [comment]
Hi! This was fixed in the latest version, its here in this github.

https://github.com/fedecalendino/alfred-emoji-mate/releases

Let me know if that fixes it for you!

Fede.

**Comment by daronspence** [comment]
Oh, I just downloaded it from the Alfred Gallery a few minutes before i opened the issue. Is there a delay to upload it there?

**Comment by fedecalendino** [comment]
Yes, I believe that currently the upload of new versions is being done manually since the gallery is in early access.

I expect that at some point they are going to add the means to automate it.
