### ISSUE TITLE
Not working when skin tone is set to "none"

### ISSUE THREAD

**Issue by awcm0n** [fedecalendino/alfred-emoji-mate#8]
When entering the keyword, "Input text to search emojis" is replaced by "Search Google for ';'" after a split second.

**Comment by fedecalendino** [comment]
I think you may have a problem with your macos installation, would you mind showing me the debug logs from Alfred? 

https://www.alfredapp.com/help/workflows/advanced/debugger/

**Comment by Camille-Upway** [comment]
I have the same issue, here's the output of the debugger:
```
[14:16:26.879] Emoji Mate[Script Filter] Queuing argument 'apple'
[14:16:27.039] Emoji Mate[Script Filter] Script with argv 'apple' finished
[14:16:27.041] ERROR: Emoji Mate[Script Filter] Code 1: Traceback (most recent call last):
  File "/Users/camille/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.4BE91E18-1EA1-44E7-8392-8000D99DC57D/./dist/main.py", line 4, in <module>
    from emojis import emojis
  File "/Users/camille/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.4BE91E18-1EA1-44E7-8392-8000D99DC57D/dist/emojis.py", line 96, in <module>
    emojis = list(build())
  File "/Users/camille/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.4BE91E18-1EA1-44E7-8392-8000D99DC57D/dist/emojis.py", line 49, in build
    if skin_tone not in key:
TypeError: 'in <string>' requires string as left operand, not NoneType
```

I think the issue is that when the skin colour selected in the workflow is None, then the environment variable `SKIN_TONE` is set to `"None"`, but the code expects it to be `""`:
https://github.com/fedecalendino/alfred-emoji-mate/blob/d6734f4d9ae3dc18e54ec3f53319a506d3536824/src/emojis.py#L7-L14

**Comment by fedecalendino** [comment]
@awcm0n / @Camille-Upway 

Thank you both!

I'll give it a look and let you know.

**Comment by fedecalendino** [comment]
I pushed `v2.0.2` here: https://github.com/fedecalendino/alfred-emoji-mate/releases/tag/v2.0.2

Would you mind checking it out to see if its fixed?

**Comment by Camille-Upway** [comment]
It works, thanks for the quick fix! 🙌
